<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-6 md:gap-8 justify-items-center w-full">
    <courseCard v-for="course in courses" :key="course.id" v-bind="course" />
  </div>
</template>

<script setup lang="ts">
import courseCard from './courseCard.vue';

const courses = [
  {
    link: '/home/course/1',
    id: 1,
    img: '/src/assets/images/course/course1.jpg',
    title: '零基礎也能成功｜手揉麵包入門全攻略',
    teacher: '張文龍',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 5800,
    originPrice: 9800,
  },
  {
    link: '/home/course/2',
    id: 2,
    img: '/src/assets/images/course/course1.jpg',
    title: '一次學會五款基礎麵包，打好烘焙基本功！',
    teacher: '陳柏烘',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 3600,
    originPrice: 9800,
  },
  {
    link: '/home/course/3',
    id: 3,
    img: '/src/assets/images/course/course1.jpg',
    title: '法式經典｜酥脆外皮、柔軟內裡的完美法國麵包',
    teacher: '王昕發',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 4500,
  },
  {
    link: '/home/course/4',
    id: 4,
    img: '/src/assets/images/course/course1.jpg',
    title: '職人級！一次掌握歐式麵包的高水量與發酵秘訣',
    teacher: '許燁堂',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 4200,
    originPrice: 9800,
  },
  {
    link: '/home/course/5',
    id: 5,
    img: '/src/assets/images/course/course1.jpg',
    title: '香濃奶油香氣四溢！手作日式生吐司！',
    teacher: '李芷甄',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 3600,
    originPrice: 9800,
  },
  {
    link: '/home/course/6',
    id: 6,
    img: '/src/assets/images/course/course1.jpg',
    title: '秒殺人氣商品！學會製作超鬆軟爆漿奶油捲',
    teacher: '林語芯',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 4800,
  },
  {
    link: '/home/course/7',
    id: 7,
    img: '/src/assets/images/course/course1.jpg',
    title: '健康新選擇！無麩質天然酵母麵包',
    teacher: '周宥蓉',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 5800,
    originPrice: 9800,
  },
  {
    link: '/home/course/8',
    id: 8,
    img: '/src/assets/images/course/course1.jpg',
    title: '亞洲風味大集合！港式、台式、日式麵包全掌握',
    teacher: '鄭皓雲',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 5800,
    originPrice: 9800,
  },
  {
    link: '/home/course/9',
    id: 9,
    img: '/src/assets/images/course/course1.jpg',
    title: '手作麵包輕體驗｜零失敗入門免費課',
    teacher: '李芷甄',
    rating: 5.0,
    students: 1238,
    hours: 11,
    price: 0,
  },
  // ... 其他課程
]
</script>
